const SET_ALERT = "ALERT/SET_ALERT";

const ADD_TO_CART = "CART/ADD_TO_CART";
const REMOVE_FROM_CART = "CART/REMOVE_FROM_CART";

const ADD_TO_CART_SAGA = "CART_SAGAS/ADD_TO_CART_SAGA";
const REMOVE_FROM_CART_SAGA = "CART_SAGAS/REMOVE_FROM_CART_SAGA";

const FIND_EMPLOYEE = "USER/FIND_EMPLOYEE";
const FIND_CUSTOMER = "USER/FIND_CUSTOMER";
const FIND_BOTH = "USER/FIND_BOTH";

const FIND_EMPLOYEE_SAGA = "USER_SAGA/FIND_EMPLOYEE_SAGA";
const FIND_CUSTOMER_SAGA = "USER_SAGA/FIND_CUSTOMER_SAGA";
const FIND_BOTH_SAGA = "USER_SAGA/FIND_BOTH_SAGA";

export {
  SET_ALERT,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ADD_TO_CART_SAGA,
  REMOVE_FROM_CART_SAGA,
  FIND_EMPLOYEE,
  FIND_EMPLOYEE_SAGA,
  FIND_CUSTOMER,
  FIND_CUSTOMER_SAGA,
  FIND_BOTH,
  FIND_BOTH_SAGA,
};
