const SET_ALERT = "ALERT/SET_ALERT";

const ADD_TO_CART = "CART/ADD_TO_CART";
const REMOVE_FROM_CART = "CART/REMOVE_FROM_CART";

const ADD_TO_CART_SAGA = "CART_SAGAS/ADD_TO_CART_SAGA";
const REMOVE_FROM_CART_SAGA = "CART_SAGAS/REMOVE_FROM_CART_SAGA";

const FIND_EMPLOYEE = "USER/FIND_EMPLOYEE";
const FIND_CUSTOMER = "USER/FIND_CUSTOMER";

export {
  SET_ALERT,
  ADD_TO_CART,
  REMOVE_FROM_CART,
  ADD_TO_CART_SAGA,
  REMOVE_FROM_CART_SAGA,
  FIND_EMPLOYEE,
  FIND_CUSTOMER,
};
