const SET_ALERT = "ALERT/SET_ALERT";

const ADD_TO_CART = "CART/ADD_TO_CART";
const REMOVE_FROM_CART = "CART/REMOVE_FROM_CART";

const FIND_EMPLOYEE = "USER/FIND_EMPLOYEE";
const FIND_CUSTOMER = "USER/FIND_CUSTOMER";

export { SET_ALERT, ADD_TO_CART, REMOVE_FROM_CART, FIND_EMPLOYEE, FIND_CUSTOMER };
